"""initial alembic

Revision ID: 5d8e78b381a3
Revises: c087c52e2cde
Create Date: 2025-08-28 14:30:39.280726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8e78b381a3'
down_revision: Union[str, None] = 'c087c52e2cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('customers')
    op.drop_table('banks')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('transaction_date', sa.DATETIME(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('banks',
    sa.Column('bank_id', sa.INTEGER(), nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), nullable=False),
    sa.Column('bank_location', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('bank_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.bank_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###
